

import { Toaster } from "react-hot-toast";
import "./globals.css";
import { Assistant} from 'next/font/google';
import GlobalProvider from "@/components/Application/GlobalProvider";


const assistant = Assistant({
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${assistant.className} antialiased`}
      >
        <GlobalProvider>
 {children}
       <Toaster position="top-center" />
        </GlobalProvider>
       
        
      </body>
    </html>
  );
}
